${pojo.getPackageDeclaration()}
// Generated by Hibernate Tools ${version}

<#assign classbody>
<#include "PojoTypeDeclaration.ftl"/> {

<#if !pojo.isInterface()>
<#include "PojoFields.ftl"/>

<#include "PojoConstructors.ftl"/>
   
<#include "PojoPropertyAccessors.ftl"/>

<#include "PojoToString.ftl"/>

<#include "PojoEqualsHashcode.ftl"/>

<#else>
<#include "PojoInterfacePropertyAccessors.ftl"/>

</#if>
<#include "PojoExtraClassCode.ftl"/>

}
</#assign>
<#assign a>${pojo.generateImports()}</#assign>
<#assign import1 = "import javax.persistence.GeneratedValue;" />
<#assign import2 = "import org.hibernate.annotations.GenericGenerator;" />
<#if (a?index_of(import1) >= 0)>
	<#assign a>${a?substring(0,a?index_of(import1))+a?substring(a?index_of(import1)+import1?length+2)}</#assign>
</#if>
<#if (a?index_of(import2) >= 0)>
	<#assign a>${a?substring(0,a?index_of(import2))+a?substring(a?index_of(import2)+import2?length+2)}</#assign>
</#if>
${a}
${classbody}

